### PR TITLE
Change tooltip markup to match the site

### PR DESCRIPTION
**Pull request by TimMoore**
The tooltips weren't displayed properly before this fix due to GitHub CSS changes.

### CODE REVIEW

**Comment by TimMoore** [comment]
Is this project still being maintained? I'd like to make a few more pull requests but it doesn't look like things are very active here...

**Comment by rodyhaddad** [comment]
Sorry for the delay. 
I pulled and tested your PR. All looks good :+1: 

I'll bump to v1.4.4. @ProLoser can you push to the chrome store?

**Comment by rodyhaddad** [comment]
I personally have most things I need already implemented in the extension. I believe that's true for @ProLoser as well. That's partly why we haven't spent much time adding new things to the extension.

Would you be interested in getting push access to the repo, so you don't have to wait for us to get your features through?

**Comment by TimMoore** [comment]
Thanks, and sorry for being impatient :smile: 

Sure, if you're happy for me to push changes, that would be great!

**Comment by ProLoser** [comment]
@TimMoore impatience is fine. Sorry about that I wasn't getting emails. Pinging me will always help as I don't have a way to add other collaborators to chrome extensions other than for testing.

**Comment by ProLoser** [comment]
Sorry about the delay, I seem to not be getting as many emails as I used to. @TimMoore your version has just been pushed and should show up in an hour.

**Pull request merged**
