### PR TITLE
feat(Github new design): cheap proposal

### LINKED ISSUE #50: New design incoming !
Hi guys 

[Github is going to change its markup](https://github.com/blog/2085-a-new-look-for-repositories)
I'm willing to help on the migration :)

### PR DESCRIPTION
**Pull request by douglasduteil**
Alright here is a cheap first proposal so we can start talking about were to put one 

proloser github omnibox after

Closes #50

### CODE REVIEW

**Comment by ProLoser** [comment]
Man sorry for missing this, I get so many notifications I don't always see them

**Comment by ProLoser** [comment]
@douglasduteil is there a way to detect what version the user is on? I too recently joined the beta. Also, what do you think about putting the badges under a dropmenu?

**Comment by douglasduteil** [comment]
Hi @ProLoser sorry for the mouth late

> is there a way to detect what version the user is on?

I don't know. I'm guessing that we can test if the `.sunken-menu` class exists in the DOM. and prioritize it over the new target (whatever it will be).

> what do you think about putting the badges under a dropmenu?

The _dropmenu_ ? You mean here ?

c3e62c10 8e58 11e5 962a c15e5a8b1ae4_2

**Comment by ProLoser** [comment]
I mean using something like this as an additional tab, something like this (of course playing around with the dropdown content and adding the badges): 
screen shot 2016-01-13 at 5 29 00 pm

**Pull request merged**
